stage 4: Training fastspeech2
++ python train_fastspeech2wContexts.py model=fastspeech2wContextswPEProsodywCurrentMel tqdm=tqdm cudnn.benchmark=false cudnn.deterministic=false data.train.utt_list=data/train.list data.train.in_dir=dump/LINE_test_sr22050/norm/train/in_fastspeech2/ data.train.out_dir=dump/LINE_test_sr22050/norm/train/out_fastspeech2/ data.dev.utt_list=data/dev.list data.dev.in_dir=dump/LINE_test_sr22050/norm/dev/in_fastspeech2/ data.dev.out_dir=dump/LINE_test_sr22050/norm/dev/out_fastspeech2/ data.batch_size=16 data.accent_info=0 data.acoustic_model=fastspeech2wContextswPEProsodywCurrentMel data.emb_dir=dump/LINE_test_sr22050/text_emb data.prosody_emb_dir=dump/LINE_test_sr22050/prosody_emb data.g_prosody_emb_dir=dump/LINE_test_sr22050/g_prosody_emb data.dialogue_info=/home/sarulab/eiji_iimori/documents/dataset/dataset/test/dialogue.txt data.use_hist_num=10 data.use_prosody_hist_num= data.use_local_prosody_hist_idx=-1 data.use_situation_text=0 train.out_dir=exp/LINE_test_sr22050_LINE_test/fastspeech2wContextswPEProsodywCurrentMel train.log_dir=tensorboard/LINE_test_sr22050_LINE_test_fastspeech2wContextswPEProsodywCurrentMel train.nepochs=500 train.sampling_rate=22050 train.mel_scaler_path=dump/LINE_test_sr22050/norm/out_fastspeech2_mel_scaler.joblib train.vocoder_name=hifigan train.vocoder_config=conf/train_hifigan/model/hifigan.yaml train.vocoder_weight_path=../fastspeech2/exp/LINE_3_sr22050_LINE_6/hifigan/latest.pth train.criterion.pitch_feature_level=1 train.criterion.energy_feature_level=1 model.netG.pitch_feature_level=1 model.netG.energy_feature_level=1 model.netG.n_mel_channel=80 model.netG.accent_info=0 model.netG.mel_embedding_mode=1 model.netG.pau_split_mode=1
/home/sarulab/eiji_iimori/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
[2022-12-21 23:50:24,677][vc_tts_template][INFO] - PyTorch version: 1.12.0+cu116
[2022-12-21 23:50:24,677][vc_tts_template][INFO] - Random seed: 773
[2022-12-21 23:50:24,677][vc_tts_template][INFO] - Fine-tuning! Loading a checkpoint: ../fastspeech2/exp/jsut_sr22050_JSUT_5/fastspeech2/latest.pth
Error executing job with overrides: ['model=fastspeech2wContextswPEProsodywCurrentMel', 'tqdm=tqdm', 'cudnn.benchmark=false', 'cudnn.deterministic=false', 'data.train.utt_list=data/train.list', 'data.train.in_dir=dump/LINE_test_sr22050/norm/train/in_fastspeech2/', 'data.train.out_dir=dump/LINE_test_sr22050/norm/train/out_fastspeech2/', 'data.dev.utt_list=data/dev.list', 'data.dev.in_dir=dump/LINE_test_sr22050/norm/dev/in_fastspeech2/', 'data.dev.out_dir=dump/LINE_test_sr22050/norm/dev/out_fastspeech2/', 'data.batch_size=16', 'data.accent_info=0', 'data.acoustic_model=fastspeech2wContextswPEProsodywCurrentMel', 'data.emb_dir=dump/LINE_test_sr22050/text_emb', 'data.prosody_emb_dir=dump/LINE_test_sr22050/prosody_emb', 'data.g_prosody_emb_dir=dump/LINE_test_sr22050/g_prosody_emb', 'data.dialogue_info=/home/sarulab/eiji_iimori/documents/dataset/dataset/test/dialogue.txt', 'data.use_hist_num=10', 'data.use_prosody_hist_num=', 'data.use_local_prosody_hist_idx=-1', 'data.use_situation_text=0', 'train.out_dir=exp/LINE_test_sr22050_LINE_test/fastspeech2wContextswPEProsodywCurrentMel', 'train.log_dir=tensorboard/LINE_test_sr22050_LINE_test_fastspeech2wContextswPEProsodywCurrentMel', 'train.nepochs=500', 'train.sampling_rate=22050', 'train.mel_scaler_path=dump/LINE_test_sr22050/norm/out_fastspeech2_mel_scaler.joblib', 'train.vocoder_name=hifigan', 'train.vocoder_config=conf/train_hifigan/model/hifigan.yaml', 'train.vocoder_weight_path=../fastspeech2/exp/LINE_3_sr22050_LINE_6/hifigan/latest.pth', 'train.criterion.pitch_feature_level=1', 'train.criterion.energy_feature_level=1', 'model.netG.pitch_feature_level=1', 'model.netG.energy_feature_level=1', 'model.netG.n_mel_channel=80', 'model.netG.accent_info=0', 'model.netG.mel_embedding_mode=1', 'model.netG.pau_split_mode=1']
Traceback (most recent call last):
  File "train_fastspeech2wContexts.py", line 212, in my_app
    model, optimizer, lr_scheduler, loss, data_loaders, writers, logger, last_epoch, last_train_iter = setup(
  File "/home/sarulab/eiji_iimori/documents/nishimura_copy/recipes/fastspeech2wContexts/../../vc_tts_template/train_utils.py", line 550, in setup
    checkpoint = torch.load(to_absolute_path(pretrained_checkpoint), map_location=device)
  File "/home/sarulab/eiji_iimori/.local/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/sarulab/eiji_iimori/.local/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/sarulab/eiji_iimori/.local/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/sarulab/eiji_iimori/documents/nishimura_copy/recipes/fastspeech2wContexts/../fastspeech2/exp/jsut_sr22050_JSUT_5/fastspeech2/latest.pth'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
